services:
  client:
    build:
      context: ./react-client
    ports:
      - "3000:3000"

  server:
    build:
      context: ./react-server
    env_file:
      - ./react-server/.env
    ports:
      - "19200:19200"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=demo_user
      - DB_PASSWORD=demo_password
      - DB_NAME=demo_db
  db:
    image: postgres:16
    container_name: demoapp-db
    restart: always
    environment:
      - POSTGRES_USER=demo_user
      - POSTGRES_PASSWORD=demo_password
      - POSTGRES_DB=demo_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
volumes:
  pgdata:
#force update
