services:
  client:
    build:
      context: https://github.com/sekharkasi/react-client.git
    ports:
      - "3000:3000"

  server:
    build:
      context: https://github.com/sekharkasi/react-server.git
    ports:
      - "5000:5000"
